### ISSUE TITLE
use :q to close current buffer and not the editor

### ISSUE THREAD

**Issue by ghedamat** [SublimeText/VintageEx#1]
I just want to notify you that in 
ghedamat/VintageEX@4e5e31bb8b071bb8161075193bdb0cc57c2e3527

I've changed the behavior of :q command to close the current buffer and not sublime_text itself 
to make it similar to what happens if you use vim with nerdtree or with vimtabs

Don't know if it can be interesting to you to implement :q in this way

Anyway many thanks for this great plugin, now I can enjoy sublime_text even more :)

**Comment by guillermooo** [comment]
That looks better than what I have now. I'll make the change. Thanks!
