### ISSUE TITLE
Command Mode

### ISSUE THREAD

**Issue by red-crown** [SublimeText/VintageEx#11]
I have been exclusively using VIM for quite some time, but I've decided to to see what st2 is all about.  In Vim, I have mapped the spacebar to entering the command line from command mode.  Is this possible with VintageEx?  I can't for the life of me figure out what commands I should be mapping to with the keybindings.

**Comment by ghost** [comment]
I use this

```
{
    "keys": [" "], "command": "vi_colon_input",
    "context":
    [
        { "key": "setting.command_mode", "operator": "equal", "operand": true }
    ]
},
{
    "keys": [" "], "command": "vi_colon_input",
    "args": {
        "initial_text": ":'<,'>"
    },
    "context":
    [
        { "key": "setting.command_mode", "operator": "equal", "operand": true },
        { "key": "selection_empty", "operator": "equal", "operand": false }
    ]
},
```

**Comment by guillermooo** [comment]
VintageEx could use better docs. I'll try to fix that. Please feel free to report issues with specific requests with this regard.

The proposed solution by @kombizenon is correct. Closing this issue.
