### ISSUE TITLE
REPLACE MODE

### ISSUE THREAD

**Issue by daryltucker** [SublimeText/VintageEx#12]
I am wondering if there is REPLACE MODE functionality within VintageEx.  I would like to use my INSERT key as a toggle between the two modes.

Currently, I am using the following keymapping setting to use INSERT to enable INSERT MODE:

```
{ "keys": ["insert"], "command": "enter_insert_mode",
  "context":
  [
        {"key": "setting.command_mode"},
        {"key": "selection_empty"}
  ]
},
```

I imagine the mode I am looking for would require the following additions:

```
{ "keys": ["insert"], "command": "enter_insert_mode",
  "context":
  [
        {"key": "setting.replace_mode"},
        {"key": "selection_empty"}
  ]
},
{ "keys": ["insert"], "command": "enter_replace_mode",
  "context":
  [
        {"key": "setting.insert_mode"},
        {"key": "selection_empty"}
  ]
},
```

My question is: **Does this functionality exist, and if so, how can I utilize it?** and **If not, are there any plans to bring this functionality to VintageEx?**

**Comment by guillermooo** [comment]
VintageEx implements a command mode only. This seems to belong in Vintage.
