### ISSUE TITLE
Search via / is not realtime anymore?

### ISSUE THREAD

**Issue by krzkrzkrz** [SublimeText/VintageEx#16]
Before this change: https://github.com/SublimeText/VintageEx/commit/5094ff3949048a9208a6e13a085482622b45459a

Typing /foobar would make the search realtime. Now, I have to press enter. Is there a way to revert this to the previous behaviour?

Second, doing /foobar. In the past, is non case sensitive. Now, it's case sensitive...

**Comment by guillermooo** [comment]
Open _Packages/VintageEx/Support/Default.sublime-keymap_ and comment this out:

```
    { "keys": ["/"], "command": "vi_search", "context": [{ "key": "setting.command_mode" }], "args": {"initial_text": "/"}},
    { "keys": ["?"], "command": "vi_search", "context": [{ "key": "setting.command_mode" }], "args": {"initial_text": "?"}},

    { "keys": ["n"], "command": "vi_repeat_search_forward", "context": [{ "key": "setting.command_mode" }]},
    { "keys": ["N"], "command": "vi_repeat_search_backward", "context": [{ "key": "setting.command_mode" }]}
```

With that you'll be back to using Vintage search, which VintageEx overrides.

In hindsight, I should have disabled the new feature by default, especially because the lack of realtime feedback. I will do that in the next build. However, Vim's `/` is also case sensitive by default.

**Comment by guillermooo** [comment]
Please leave this one open for now so I remember to disable this at some point :)

**Comment by krzkrzkrz** [comment]
On the case sensitive issue. Would be great if we could set searches to ingore case. Something like: http://stackoverflow.com/questions/2287440/how-to-do-case-insensitive-search-in-vim

I know some people prefer case sensitive and non-case sensitive searches, depending on the scenario.

**Comment by guillermooo** [comment]
Addressed in 189d522684b01f9d77f22a26b756bf0957d121df.

**Comment by krzkrzkrz** [comment]
Does this also fix the case insensitive search option?

**Comment by guillermooo** [comment]
Not yet, I've entered a separate issue for that (#19).
