### ISSUE TITLE
Wall, buffers, registers, files.... commands dont work

### ISSUE THREAD

**Issue by ghost** [SublimeText/VintageEx#23]
Some of the commands don't do anything: wall, buffers (ls works), files, registers, x. 

Console output: 

ex_command(name=u'files', command='ex_prompt_select_open_file', forced=False, args={}, parse_errors=[], line_range={'right_ref': None, 'left_offset': None, 'text_range': u'', 'right_offset': None, 'left_ref': None, 'left_search_offsets': [], 'separator': None, 'right_search_offsets': []}, can_have_range=True)
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
TypeError: run() got an unexpected keyword argument 'line_range'

All command have the same output (last 2 lines). Window 7 64x, Dev channel build 2220

**Comment by guillermooo** [comment]
Some commands were missing `ex_error.ERR_NO_RANGE_ALLOWED` so they won't get passed and additional `line_range` argument. This requirement has become more strict after the rewrite of the command line parser. They should work fine now, though. Thanks for the report!

**Comment by ghost** [comment]
"exit" and "x" still throw the same error, others are ok

**Comment by guillermooo** [comment]
Addressed at e9f1140f531dfd1d9dffc8b9985b1e6d94f6ef5e.

**Comment by ghost** [comment]
now ":line_number" doesnt work:

ex_command(name=':', command='ex_goto', forced=False, args={}, parse_errors=[], line_range={'right_ref': None, 'left_offset': 10, 'text_range': u'10', 'right_offset': None, 'left_ref': None, 'left_search_offsets': [], 'separator': None, 'right_search_offsets': []}, can_have_range=True)
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
  File ".\ex_commands.py", line 120, in run
ValueError: need more than 1 value to unpack

And I think "!" also has problems:

ex_command(name='!', command='ex_shell_out', forced=False, args={'shell_cmd': u'dir'}, parse_errors=[], line_range={'right_ref': None, 'left_offset': None, 'text_range': u'', 'right_offset': None, 'left_ref': None, 'left_search_offsets': [], 'separator': None, 'right_search_offsets': []}, can_have_range=True)
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
  File ".\ex_commands.py", line 139, in run
  File ".\vex\shell.py", line 9, in run_and_wait
TypeError: run_and_wait() takes exactly 1 argument (2 given)

**Comment by guillermooo** [comment]
Addressed at 144dabf29d7ea21e6ce1c79b16c095aff5a7963f.
