### ISSUE TITLE
pipe through shell does not seem to work

### ISSUE THREAD

**Issue by acidtv** [SublimeText/VintageEx#26]
When trying to pipe my buffer through sort with :%!sort nothing seems to happen.

It also doesn't give an error message.

I'm running osx 10.5.7 and sb 2.0.1

**Comment by guillermooo** [comment]
VintageEx will process lines one by one, launching the requested command for each line in turn, so what you want to do won't work at the moment. This should probably be fixed.

Sublime Text has built-in commands for sorting, though, so you can press F9 to sort all selected lines.

**Comment by acidtv** [comment]
Ah, thanks for the tip. Would be niced to have it fixed though :)

**Comment by guillermooo** [comment]
Let me know if the fix works for you now. It seems to work fine on Windows.

**Comment by acidtv** [comment]
It works with visual blocks now :).

But selecting all lines with :%!sort still doesn't work.

**Comment by guillermooo** [comment]
For `%` lines will always be split by newlines at the moment. I'll take a look at it.

**Comment by guillermooo** [comment]
Fixed at 8043d3edfb960f374038e77a2acef3c287f36a48.

**Comment by acidtv** [comment]
Confirmed. Thanks alot! :)
