### ISSUE TITLE
Vintage's "*" and "#" are not repeatable anymore 

### ISSUE THREAD

**Issue by ghost** [SublimeText/VintageEx#28]
VintageEx breaks Vintage \* and # (search under the cursor) commands, so you cant repeat them with "n" or "N" (it probably breaks "n" commands, because search works). You have to repeat them in order to find next occurrences.

I have tried with VintageEx disabled and they work as they should

**Comment by guillermooo** [comment]
It won't work for both until the search functionality in VintageEx is moved to Vintage. I'll have to disable `n` and `N` for VintagaEx.

**Comment by guillermooo** [comment]
I'm not sure it's a good idea, but fixed at 144dabf29d7ea21e6ce1c79b16c095aff5a7963f.
