### ISSUE TITLE
Command/Search Bar should be closed after hitting enter

### ISSUE THREAD

**Issue by VxJasonxV** [SublimeText/VintageEx#4]
After running a search (via / or ?), or issuing a command (:s), the bar should be closed. Not closing the bar prevents you from immediately pressing 'n' or 'N' to re-run the last search. Generally it prevents you from doing anything without first hitting 'Esc', which can be frustrating when coming from a vim background (or going to vim in the future).

**Comment by jtmkrueger** [comment]
+1 for this.  Seems like a good issue being as the flow differs from vim.

**Comment by guillermooo** [comment]
**Searching with / and ?**

I suppose you're referring to Vintage here? VintageEx doesn't currently implement this functionality, but Vintage does. AFAIK, it behaves the desired way: the search bar will be dismissed after pressing `Enter` or `Esc`.

**Replacing with :s**

The input panel should go away too and return focus to the buffer. Are you seeing anything different?

Could you please specify your platform?

**Comment by VxJasonxV** [comment]
Considering Vintage itself is shipped with and declared as an ignored package, I think it would simply be a better idea to file this directly with the Sublime Text devs.
