### ISSUE TITLE
Map ; key to :

### ISSUE THREAD

**Issue by linjunpop** [SublimeText/VintageEx#42]
Like vim `nmap ; :`

**Comment by linjunpop** [comment]
``` json
[
  {
    "keys": [";"], "command": "vi_colon_input",
    "context":
    [
      { "key": "setting.command_mode", "operator": "equal", "operand": true }
    ]
  }
]
```

**Comment by guillermooo** [comment]
This isn't a standard command, so I don't think it should be included in the default configuration. You can add this to your _Preferences - User_ file and it should work, though.

**Comment by linjunpop** [comment]
Ok, thanks :beer:
