### ISSUE TITLE
can't indent multiple lines using n> in visual mode

### ISSUE THREAD

**Issue by leeahoward** [SublimeText/VintageEx#43]
I am looking for functionality described here:
http://stackoverflow.com/questions/235839/how-do-i-indent-multiple-lines-quickly-in-vi

Action:select a block of text in visual mode and the hit n> to indent, where n is the number of times to indent.

Expected Behavior:the selected text is indented n times. 

Actual Behavior: the text is indented once and the first line selected is indented n times.

**Comment by guillermooo** [comment]
This feature is provided by Vintage, not VintageEx. You should report it there instead.

**Comment by leeahoward** [comment]
Will do.. Thanks
