### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by cureau** [SublimeText/VintageEx#44]
Thanks for this plugin!  Small bug/feature-request:

returns "No Range Allowed" error if `/joe/s-2` is attempted (or any advanced search).

Seems to have all the advanced search and replace features, but not advance search, such as many of the search examples found in:

http://www.rayninfo.co.uk/vimtips.html

**Comment by guillermooo** [comment]
That would be nice to have, but it isn't in the cards short-term. You can leave the issue open as a reminder, though.
