### ISSUE TITLE
Make search with '/' act like in vim, e.g. as movement command

### ISSUE THREAD

**Issue by alfa07** [SublimeText/VintageEx#48]
One of really fast ways to move in vim is to use '/'. At the moment it is practically difficult in VintageEx. Suggestion:
1. '/' search shouldn't interfere with selection, it should act as a movement command
   - if in normal mode then just move - without selecting anything (see vim)
   - if in visual mode then extend selection
2. Act as movement command and be combinable with other commands, e.g.

There is a fox in the forest.
^
d/for<CR> leads to
forest.

**Comment by guillermooo** [comment]
VintageEx is no longer maintained. Development continues in Vintageous and VintageousEx.
