### ISSUE TITLE
SublimeText 3 support

### ISSUE THREAD

**Issue by jcartledge** [SublimeText/VintageEx#49]
Hi,

I have a fork which works in ST3 [here](https://github.com/jcartledge/VintageEx/compare/st3?w=0) - the downside is it breaks in ST2. 

The changes are:
- automated 2to3 Python stdlib changes - not sure these can be made backwards compatible,
- changes to imports to make them relative - not sure these can be made backwards compatible,
- one SublimeText API change (add_regions) which (I believe) is backwards compatible as it changes a positional to a named keyword.

I don't know if this is helpful to the project. Obviously it can't be merged as is because it breaks ST2 compatibility.

I know there are efforts underway to rewrite Vintage and VintageEx to ST3, but I'm not sure how far along they are, or what the transition process will be. Can anyone address this?

**Comment by guillermooo** [comment]
VintageousEx is being ported to S3 here:

https://github.com/guillermooo/VintageousEx

Vintageous is a rewrite of Vintage:

https://github.com/guillermooo/Vintageous
