### ISSUE TITLE
substitute command replaces non-selected lines

### ISSUE THREAD

**Issue by codingcampbell** [SublimeText/VintageEx#5]
Thanks for this great plugin. The lack of the `:s/` command was keeping me from using Sublime full-time.

Also, FYI: I'm using Sublime 2 build #2161 on Ubuntu 10.04 64-bit. My VintageEx version is 11.10.3 according to PKG-INFO

Sorry I don't have the expertise to patch this myself ..

Say you have this code:

```
foo.bar = foo.baz;
bar.foo = baz;
```

Let's say I need to rename the `foo` variable on the first line.

If I enter visual-line-mode (shift+v), then `:s/foo/whatever/g`, the output is:

```
whatever.bar = whatever.baz;
bar.whatever = baz;
```

The expected output is:

```
whatever.bar = whatever.baz;
bar.foo = baz;
```

The bug only "bleeds over" 1 extra line. Also, the bug does not happen in regular visual mode.

Please let me know if I can help further.

Thanks again,
-- Matt

**Comment by guillermooo** [comment]
I've fixed this. Let me know if it works for you now.

**Comment by codingcampbell** [comment]
Thanks for addressing this so quickly. It works perfectly :)
