### ISSUE TITLE
Problem installing/running VintageEx

### ISSUE THREAD

**Issue by mikijov** [SublimeText/VintageEx#7]
I run latest Sublime 2181 on OSX 10.7.3. I installed it by copying VintageEx.sublime-package into "Installed Packages". When I run Sublime the Ex commands are not working. I tried simply :q and nothing. Inspection of the Console does reveal some errors while loading VintageEx. 

=== console output ===

startup, version: 2181 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/miki/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/miki/Library/Application Support/Sublime Text 2/Settings
error parsing session: No data at: 0:0
PackageSetup not required
catalogue loaded
found 7 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 1 files for base name Main.sublime-menu
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage_commands.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage_motions.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_command_parser.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_commands.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./ex_commands.py", line 18, in <module>
    import shell
  File "./shell.py", line 1, in <module>
    import plat
ImportError: No module named plat
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_error.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_location.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_range.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/shell.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./shell.py", line 1, in <module>
    import plat
ImportError: No module named plat
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/vintage_ex.py
plugin init time: 0.13851
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.299545
using gamma: 2 (err: 6.9282)
startup cache, total files: 92 cache hits: 92
startup time: 0.428839 (package setup was not run)
loaded 934 snippets
ex_command(name=u'q', command='ex_quit', forced=False, range=None, args={}, parse_errors=[])
ex_command(name=u'q', command='ex_quit', forced=False, range=None, args={}, parse_errors=[])
ex_command(name=u'q', command='ex_quit', forced=False, range=None, args={}, parse_errors=[])

**Comment by guillermooo** [comment]
Is your install actually missing the plat module inside the VintageEx package? I believe module importing was tweaked recently by Jon, and although I'm pretty sure VintageEx is at fault here, I have no way of testing on Macs, unfortunately. Everything works fine on Linux and Windows AFAIK.

**Comment by mikijov** [comment]
What is plat? :-) We'll get there I am sure, but for now I am only a user with no python or sublime experience.

I just installed VintageEx using Package Control on a different Mac, and sure enough, it is working. On the original Mac I installed by following the instructions from the main page, installation section. I downloaded the "latest version" and put it into "Installed Packages" folder. So it might be an issue with that installer. I will check tomorrow if there is any difference in the unpacked folder "Packages".

The console log on the properly installed computer has errors in a different place, so I am still worried that something might be a miss. Here is the new log.

=== log ===

startup, version: 2181 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/miki/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/miki/Library/Application Support/Sublime Text 2/Settings
error parsing session: No data at: 0:0
PackageSetup not required
catalogue loaded
found 7 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage_commands.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/Vintage/vintage_motions.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_command_parser.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_commands.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_error.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_location.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/ex_range.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/setup.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./setup.py", line 589, in <module>
    url='sublimetext.info',
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/core.py", line 106, in setup
    attrs['script_name'] = os.path.basename(sys.argv[0])
AttributeError: 'module' object has no attribute 'argv'
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/shell.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/test_runner.py
Reloading plugin /Users/miki/Library/Application Support/Sublime Text 2/Packages/VintageEx/vintage_ex.py
plugin init time: 0.338771
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.591979
using gamma: 2 (err: 6.9282)
startup cache, total files: 94 cache hits: 94
startup time: 0.701382 (package setup was not run)
loaded 934 snippets
Package Control: Skipping automatic upgrade, last run at 2012-02-22 21:18:44, next run at 2012-02-22 22:18:44 or after
Unable to open /Users/miki/Library/Application Support/Sublime Text 2/Packages/User/JSON.sublime-settings

**Comment by guillermooo** [comment]
Ouch! Yeah, the build is broken. "plat" is missing altogether from the packaged distribution. Cloning the repo will fill the new directory with garbage, although it should work atm.

**Comment by mikijov** [comment]
At least I am not going crazy. Please update the issue with any progress, and I will be happy to try it if you need a test.

**Comment by guillermooo** [comment]
Reposted the package. Let me know whether it works now.

**Comment by mikijov** [comment]
Completely removed old VintageEx, installed by dropping .package into "Installed Packages", it installed properly and I see no more error messages in the console. Quick test of basic commands worked as well. It seems resolved now.

Thanks.
