### ISSUE TITLE
executing shell commands fails on linux with SubLime Text 2 Build 2181

### ISSUE THREAD

**Issue by fibbs** [SublimeText/VintageEx#8]
tried: <escape>:!ls<enter>

error message:
Package Control: No updated packages
ex_command(name=u'!', command='ex_shell_out', forced=False, range=None, args={'shell_cmd': u'ls'}, parse_errors=[])
Traceback (most recent call last):
  File "./sublime_plugin.py", line 344, in run_
  File "./ex_commands.py", line 134, in run
  File "./shell.py", line 10, in run_and_wait
  File "./plat/linux.py", line 9, in run_and_wait
  File ".\subprocess.py", line 633, in **init**
  File ".\subprocess.py", line 1139, in _execute_child
OSError: [Errno 2] No such file or directory

**Comment by guillermooo** [comment]
This should be partially fixed in the next build.

**Comment by guillermooo** [comment]
The `$TERMINAL` wasn't being retrieved properly. It should work now.

**Comment by lingo** [comment]
Having similar problem with Sublime 2.0.1 build 2217, in that on my linux box, neither $TERM or $COLORTERM are giving any result, so the shell isn't running.  Perhaps there should be a fallback or a config option?

**Comment by guillermooo** [comment]
Definitely. I'm a casual Linux user, but my latest research led me to believe one cannot retrieve the user's preferred shell easily? I have a working Ubuntu install on my laptop now, so I will test there soon.

**Comment by lingo** [comment]
Well, if the user is on a Debian-based distro, you can usually rely on /etc/alternatives/x-terminal-emulator to be a symlink to something useful.  This works for Ubuntu.  Not sure this will help much for other flavours of linux though.

**Comment by guillermooo** [comment]
Addressed at ef136babc5c44548ccf613abb914506de0c14d53.
