### ISSUE TITLE
Substitute (:s/foo/bar) always returns "No pattern available"

### ISSUE THREAD

**Issue by tnorthcutt** [SublimeText/VintageEx#9]
Regardless of the text on the current line, :s/foo/bar always returns "VintageEx: No pattern available."

I've tried it with forward slashes, spaces, and back slashes as the separators, but to no avail.

This is on Windows 7 64-bit.

**Comment by weslly** [comment]
The correct syntax is (the whole file):

```
:%s/foo/bar/g
```

Or (only the current line):

```
:s/foo/bar/g
```

**Comment by guillermooo** [comment]
As weslly says, currently the trailing separator is needed, even if you're not using flags, but this is inconsistent with Vim.

**Comment by tnorthcutt** [comment]
Ahh, thank you for the correction. Do you happen to know what it would take to eliminate the need for the trailing separator and flag?

**Comment by guillermooo** [comment]
I'll have to revise this command:

https://github.com/SublimeText/VintageEx/blob/master/ex_commands.py#L415

**Comment by guillermooo** [comment]
(Please don't close this issue as it's really a defect.)

**Comment by guillermooo** [comment]
Fixed in 8a8ff5953e0b817a92d3d45dda608609b1152fef
